config/routes.rb
Rails.application.routes.draw do
  
  mount Ckeditor::Engine => '/ckeditor'
  root 'products#index'
  
  resources :orders do 
     
     member do
      get :pay_with_credit_card 
      post :pay2go_cc_notify
      post :pay2go_cvs_notify
      post :pay2go_atm_complete
     end
    
  end
  
  resources :products do 
    
    member do
        post :add_to_cart
    end
  end
  
  
  resources :carts do
     collection do
       post :checkout
       delete :clean
     end
  end
  
  resources :items , controller: "cart_items"
 
  devise_for :users
  namespace :admin do
    resources :products
    resources :orders do
      member do
        post :cancel
        post :ship
        post :shipped
        post :return
      end
    end
  end
  
  namespace :account do
    
    resources :orders
  end

end

app/models/cart.rb
class Cart < ActiveRecord::Base
    
    has_many :cart_items , :dependent => :destroy
    has_many :items , :through => :cart_items , :source => :product
    
    def find_cart_item(product)
        
        cart_items.find_by(product: product)    
    end
    
    def add_product_to_cart(product)
        
        items << product
    
    end
    
    def total_price
        
          # items.inject(0) { |sum, item| sum + item.price }
          cart_items.inject(0) { |sum, item| sum + (item.product.price * item.quantity) }
          
          #sum = 0
          
         # items.each do |item|
         #    sum = sum + item.price
         # end
          
          #return sum    
    end
    
    def clean!
        
        cart_items.destroy_all
        
    end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
    
    before_action :authenticate_user!, only: [:checkout]
    
    def index
        
        if current_cart.cart_items.count <= 0
            flash[:warning] = "目前購物車是空的,請先加入商品!"
            redirect_to products_path
        end
        
    end
    
    def checkout
        
        @order = current_user.orders.build
        @info  = @order.build_info
    end
    
    def clean
        
        current_cart.clean!
        flash[:warning] = "已清空購物車"
        redirect_to carts_path
        
    end
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/carts_helper.rb
module CartsHelper
    
    
    def render_cart_total_price(cart)
        
            cart.total_price
    end
end

app/views/carts/checkout.html.erb
<div class="row">
   <div class="col-md-12">

    <h2> 購物明細 </h2>

    <table class="table table-bordered">
      <thead>
        <tr>
          <th width="80%">商品明細</th>
          <th>單價</th>
          <th>數量</th>
        </tr>
      </thead>
      <tbody>

        <% current_cart.items.each do |product| %>
          <tr>
            <td>
              <%= link_to(product.title, product_path(product)) %>
            </td>
            <td>
              <%= product.price %>
            </td>
             <td>
              <%= current_cart.find_cart_item(product).quantity %>
            </td>
          </tr>
        <% end %>

      </tbody>
    </table>

    <div class="total clearfix">
      <span class="pull-right">
        總計 <%= render_cart_total_price(current_cart) %> NTD
      </span>
    </div>

    <hr>

    <h2> 訂單資訊 </h2>

    <div class="order-form">

      <%= simple_form_for @order do |f| %>

        <%= f.simple_fields_for :info do |c| %>

          <legend> 訂購人</legend>
          <div class="form-group col-lg-6">
            <%= c.input :billing_name  %>
          </div>
          <div class="form-group col-lg-6">
            <%= c.input :billing_address  %>
          </div>

          <legend> 收貨人</legend>
          <div class="form-group col-lg-6">
           <%= c.input :shipping_name  %>
          </div>
          <div class="form-group col-lg-6">
            <%= c.input :shipping_address  %>
          </div>
        <% end %>

        <div class="checkout">
          <%= f.submit "生成訂單", class: "btn btn-lg btn-danger pull-right",
                       data: { disable_with: "Submitting..." } %>
        </div>
      <% end %>

    </div>
  </div>
</div>

app/views/carts/index.html.erb
<div class="row">
  <div class="col-md-12">
    
    <%= link_to("清空購物車", clean_carts_path ,
         method: :delete , class: "pull-right",
               style: "text-decoration: underline;",
               data: { confirm: "你確定要清空整個購物車嗎？"} )%>
               
    <h2> 購物車 </h2>

    <table class="table table-bordered">
      <thead>
        <tr>
          <th colspan="2">商品資訊</th>
          <th>單價</th>
          <th>操作選項</th>
          <th>數量</th>
        </tr>
      </thead>
      <tbody>

        <% current_cart.items.each do |product| %>
          <tr>
            <td>
              <%= render_product_photo(product.default_photo) %>
            </td>
            <td>
              <%= link_to(product.title, product_path(product)) %>
            </td>
            <td>
              <%= product.price %>
            </td>
           
             <td>
              <%= link_to item_path(product), method: :delete do %>
                <i class="fa fa-trash"></i>
              <% end %>
            </td>
            
            <td>
              <% item = current_cart.find_cart_item(product) %>

              <%= form_for item, url: item_path(product) do |f| %>
                <%= f.select :quantity, 1..product.quantity %>
                <%= f.submit "更新", data: { disable_with: "Submiting..." } %>
              <% end -%>
            </td> 
          
          </tr>
        <% end %>

      </tbody>
    </table>

    <br>

    <div class="total clearfix">
      <span class="pull-right">
         <span> 總計 <%=render_cart_total_price(current_cart)%> NTD  </span>
      </span>
    </div>

    <hr>

    <div class="checkout clearfix">
      <%= link_to("確認結賬", checkout_carts_path , method: :post, class: "btn btn-lg btn-danger pull-right") %>
    </div>
  </div>
</div>