config/routes.rb
Rails.application.routes.draw do
  
  mount Ckeditor::Engine => '/ckeditor'
  root 'products#index'
  
  resources :orders do 
     
     member do
      get :pay_with_credit_card 
      post :pay2go_cc_notify
      post :pay2go_cvs_notify
      post :pay2go_atm_complete
     end
    
  end
  
  resources :products do 
    
    member do
        post :add_to_cart
    end
  end
  
  
  resources :carts do
     collection do
       post :checkout
       delete :clean
     end
  end
  
  resources :items , controller: "cart_items"
 
  devise_for :users
  namespace :admin do
    resources :products
    resources :orders do
      member do
        post :cancel
        post :ship
        post :shipped
        post :return
      end
    end
  end
  
  namespace :account do
    
    resources :orders
  end

end

app/models/product.rb
class Product < ActiveRecord::Base
    
    has_many :photos
    
    accepts_nested_attributes_for :photos
    
    def default_photo
        photos.last
    end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
    layout "admin"
    before_action :authenticate_user!
    before_action :admin_required
    
    def index
        @products = Product.order("id DESC ")
    end
    def show
        
        @product = Product.find(params[:id])
        
    end
    def edit
        @product = Product.find(params[:id])
    end
    
    def update
        
        @product = Product.find(params[:id])
        
        if @product.update(product_params)
            
            redirect_to admin_products_path
        else
            render :edit
            
        end
    end
    

    def new
       
       @product = Product.new
       @photo =@product.photos.new
       
    end
    
    def create
        
        @product = Product.new(product_params)
        
        if @product.save
        
           redirect_to admin_products_path 
        else
           render :new 
        end
    end
    
    
    private
    
    def product_params
        
        params.require(:product).permit(:title,:description,:quantity,:price, photos_attributes: [:image])
    end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    
    def index
    
          @products = Product.order("id DESC ")   
    end
    
    def show
        @product = Product.find(params[:id])
    end
    
    def add_to_cart
        
       @product =  Product.find(params[:id])
       if !current_cart.items.include?(@product) 
           
           current_cart.add_product_to_cart(@product)
           flash[:notice] = "你已經成功將#{@product.title}加入"
       else
           flash[:warning] = "你購物車已經有此商品"
       end
       
       redirect_to :back
    end
    
    
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
    
    def render_product_photo(photo ,size="thumb")
        
        if photo.present?
            
           
            image_url = photo.image.send(size).url
        else
           
            image_url=render_no_pic_url(size)
        end
        
        image_tag(image_url,class:"thumbnail")
    end
    
    def render_no_pic_url(size)
        
        case size
        when :medium
            volume = "300X300"
        else
             volume= "200X200"
        end
        
        return "http://placehold.it/#{volume}&text=No Pic"
    end
    
    def render_cart_items_count(cart)
        
        cart.cart_items.count
        
    end
    
end

app/views/admin/products/edit.html.erb
<h2>修改產品</h2>

<%= simple_form_for [:admin, @product] do |f| %>

  <div class="group">
  
    <%=f.input :title %>
  </div>

  <div class="group">

    
     <%=f.input :description , :as => :ckeditor, :input_html => { :ckeditor => {:toolbar => 'Full'} }  %>
  </div>

  <div class="group">
   
    
     <%=f.input :quantity %>
  </div>

  <div class="group">

     <%=f.input :price %>
  </div>

  <%= f.submit "Submit", data: { disable_with: "Submitting..." } %>

<% end %>

app/views/admin/products/index.html.erb
<h2> Product List </h2>

<div class="pull-right" style="padding-bottom: 20px;">
  <%= link_to("新增產品", new_admin_product_path, class: "btn btn-primary btn-sm") %>
</div>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>#</th>
      <th width="220">Product Pic</th>
      <th>Name</th>
      <th>Price</th>
      <th width="100"> Options</th>
    </tr>
  </thead>
  <tbody>

    <% @products.each do |product| %>
      <tr>
        <td>
          <%= product.id %>
        </td>
        <td>
          <%= render_product_photo(product.default_photo) %>
        </td>
        <td>
          <%= product.title %>
        </td>
        <td>
          <%= product.price %>
        </td>
        <td>
          <%= link_to("Edit", edit_admin_product_path(product)) %>
        </td>
      </tr>
    <% end %>

  </tbody>
</table>

app/views/admin/products/new.html.erb
<h2>新增產品</h2>

<%= simple_form_for [:admin, @product] do |f| %>

  <div class="group">
  
    <%=f.input :title %>
  </div>

  <div class="group">

    
     <%=f.input :description , :as => :ckeditor, :input_html => { :ckeditor => {:toolbar => 'Full'} } ,:class => 'ckeditor' %>
  </div>

  <div class="group">
   
    
     <%=f.input :quantity %>
  </div>

  <div class="group">

     <%=f.input :price %>
  </div>
   <div class="group">

   <%=f.simple_fields_for :photos do |c| %>
       <%=c.input :image , as: :file %>
   <% end %>
  </div>

  <%= f.submit "Submit", data: { disable_with: "Submitting..." } %>

<% end %>