config/routes.rb
Rails.application.routes.draw do
  
  mount Ckeditor::Engine => '/ckeditor'
  root 'products#index'
  
  resources :orders do 
     
     member do
      get :pay_with_credit_card 
      post :pay2go_cc_notify
      post :pay2go_cvs_notify
      post :pay2go_atm_complete
     end
    
  end
  
  resources :products do 
    
    member do
        post :add_to_cart
    end
  end
  
  
  resources :carts do
     collection do
       post :checkout
       delete :clean
     end
  end
  
  resources :items , controller: "cart_items"
 
  devise_for :users
  namespace :admin do
    resources :products
    resources :orders do
      member do
        post :cancel
        post :ship
        post :shipped
        post :return
      end
    end
  end
  
  namespace :account do
    
    resources :orders
  end

end

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand" href="/">購物中心(測試)</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active">
          <%= link_to("Products", products_path) %>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
         <li>
          <%= link_to carts_path do  %>
            購物車 <i class="fa fa-shopping-cart"> </i> (<%=render_cart_items_count(current_cart)%>)
          <% end %>
        </li>
        
        <% if !current_user %>
          <li> <%= link_to("登入", new_user_session_path) %> </li>
        <% else %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Hi!, <%= current_user.email %>
              <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <% if current_user.admin?%>
              <li>
                <%= link_to("Admin 表單",admin_products_path ) %>
              </li>
              <% end %>
               <li>
                <%= link_to("個人訂單列表", account_orders_path ) %>
              </li>
              <li>
                <%= link_to("登出", destroy_user_session_path, method: :delete ) %>
              </li>
            </ul>
          </li>
        <% end %>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>